#Representation name (used for naming output files):
representation_name: KeAP20

#Benchmarks (should be one of the "similarity","family","function","affinity","all"):
# "similarity" for running protein semantic similarity inference benchmark
# "function" for running ontology-based function prediction benchmark
# "family" for running drug target protein family classification benchmark
# "affinity" for running protein-protein binding affinity estimation benchmark
# "all" for running all benchmarks
benchmark: similarity

#Path of the file containing representation vectors of UniProtKB/Swiss-Prot human proteins:
representation_file_human: /mnt/bd/medai-kprotein/protein_function_prediction/PROBE/KeAP20_human_embedding.csv

#Path of the file containing representation vectors of samples in the SKEMPI dataset: 
representation_file_affinity: /mnt/bd/medai-kprotein/protein_function_prediction/PROBE/KeAP20_SKEMPI_embedding.csv


#Semantic similarity inference benchmark dataset (should be a list that includes any combination of "Sparse", "200", and "500"):
similarity_tasks: ["Sparse"]

#Ontology-based function prediction benchmark dataset in terms of GO aspect (should be one of the following: "MF", "BP", "CC", or "All_Aspects"):
function_prediction_aspect: All_Aspects

#Ontology-based function prediction benchmark dataset in terms of size-based-splits (should be one of the following: "High", "Middle", "Low", or "All_Data_Sets")
function_prediction_dataset: All_Data_Sets

#Drug target protein family classification benchmark dataset in terms of similarity-based splits (should be a list that includes any combination of "nc", "uc50", "uc30", and "mm15")
family_prediction_dataset: ["nc","uc50","uc30","mm15"]

#Detailed results (can be True or False)
detailed_output: False
